//
// asio.hpp
// ~~~~~~~~
//
// Copyright (c) 2003-2024 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#ifndef ASIO_HPP
#define ASIO_HPP

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
# pragma once
#endif // defined(_MSC_VER) && (_MSC_VER >= 1200)

#include <Asio/any_completion_executor.hpp>
#include <Asio/any_completion_handler.hpp>
#include <Asio/any_io_executor.hpp>
#include <Asio/append.hpp>
#include <Asio/as_tuple.hpp>
#include <Asio/associated_allocator.hpp>
#include <Asio/associated_cancellation_slot.hpp>
#include <Asio/associated_executor.hpp>
#include <Asio/associated_immediate_executor.hpp>
#include <Asio/associator.hpp>
#include <Asio/async_result.hpp>
#include <Asio/awaitable.hpp>
#include <Asio/basic_datagram_socket.hpp>
#include <Asio/basic_deadline_timer.hpp>
#include <Asio/basic_file.hpp>
#include <Asio/basic_io_object.hpp>
#include <Asio/basic_random_access_file.hpp>
#include <Asio/basic_raw_socket.hpp>
#include <Asio/basic_readable_pipe.hpp>
#include <Asio/basic_seq_packet_socket.hpp>
#include <Asio/basic_serial_port.hpp>
#include <Asio/basic_signal_set.hpp>
#include <Asio/basic_socket.hpp>
#include <Asio/basic_socket_acceptor.hpp>
#include <Asio/basic_socket_iostream.hpp>
#include <Asio/basic_socket_streambuf.hpp>
#include <Asio/basic_stream_file.hpp>
#include <Asio/basic_stream_socket.hpp>
#include <Asio/basic_streambuf.hpp>
#include <Asio/basic_waitable_timer.hpp>
#include <Asio/basic_writable_pipe.hpp>
#include <Asio/bind_allocator.hpp>
#include <Asio/bind_cancellation_slot.hpp>
#include <Asio/bind_executor.hpp>
#include <Asio/bind_immediate_executor.hpp>
#include <Asio/buffer.hpp>
#include <Asio/buffer_registration.hpp>
#include <Asio/buffered_read_stream_fwd.hpp>
#include <Asio/buffered_read_stream.hpp>
#include <Asio/buffered_stream_fwd.hpp>
#include <Asio/buffered_stream.hpp>
#include <Asio/buffered_write_stream_fwd.hpp>
#include <Asio/buffered_write_stream.hpp>
#include <Asio/buffers_iterator.hpp>
#include <Asio/cancellation_signal.hpp>
#include <Asio/cancellation_state.hpp>
#include <Asio/cancellation_type.hpp>
#include <Asio/co_spawn.hpp>
#include <Asio/completion_condition.hpp>
#include <Asio/compose.hpp>
#include <Asio/connect.hpp>
#include <Asio/connect_pipe.hpp>
#include <Asio/consign.hpp>
#include <Asio/coroutine.hpp>
#include <Asio/deadline_timer.hpp>
#include <Asio/defer.hpp>
#include <Asio/deferred.hpp>
#include <Asio/detached.hpp>
#include <Asio/dispatch.hpp>
#include <Asio/error.hpp>
#include <Asio/error_code.hpp>
#include <Asio/execution.hpp>
#include <Asio/execution/allocator.hpp>
#include <Asio/execution/any_executor.hpp>
#include <Asio/execution/blocking.hpp>
#include <Asio/execution/blocking_adaptation.hpp>
#include <Asio/execution/context.hpp>
#include <Asio/execution/context_as.hpp>
#include <Asio/execution/executor.hpp>
#include <Asio/execution/invocable_archetype.hpp>
#include <Asio/execution/mapping.hpp>
#include <Asio/execution/occupancy.hpp>
#include <Asio/execution/outstanding_work.hpp>
#include <Asio/execution/prefer_only.hpp>
#include <Asio/execution/relationship.hpp>
#include <Asio/executor.hpp>
#include <Asio/executor_work_guard.hpp>
#include <Asio/file_base.hpp>
#include <Asio/generic/basic_endpoint.hpp>
#include <Asio/generic/datagram_protocol.hpp>
#include <Asio/generic/raw_protocol.hpp>
#include <Asio/generic/seq_packet_protocol.hpp>
#include <Asio/generic/stream_protocol.hpp>
#include <Asio/handler_continuation_hook.hpp>
#include <Asio/high_resolution_timer.hpp>
#include <Asio/io_context.hpp>
#include <Asio/io_context_strand.hpp>
#include <Asio/io_service.hpp>
#include <Asio/io_service_strand.hpp>
#include <Asio/ip/address.hpp>
#include <Asio/ip/address_v4.hpp>
#include <Asio/ip/address_v4_iterator.hpp>
#include <Asio/ip/address_v4_range.hpp>
#include <Asio/ip/address_v6.hpp>
#include <Asio/ip/address_v6_iterator.hpp>
#include <Asio/ip/address_v6_range.hpp>
#include <Asio/ip/network_v4.hpp>
#include <Asio/ip/network_v6.hpp>
#include <Asio/ip/bad_address_cast.hpp>
#include <Asio/ip/basic_endpoint.hpp>
#include <Asio/ip/basic_resolver.hpp>
#include <Asio/ip/basic_resolver_entry.hpp>
#include <Asio/ip/basic_resolver_iterator.hpp>
#include <Asio/ip/basic_resolver_query.hpp>
#include <Asio/ip/host_name.hpp>
#include <Asio/ip/icmp.hpp>
#include <Asio/ip/multicast.hpp>
#include <Asio/ip/resolver_base.hpp>
#include <Asio/ip/resolver_query_base.hpp>
#include <Asio/ip/tcp.hpp>
#include <Asio/ip/udp.hpp>
#include <Asio/ip/unicast.hpp>
#include <Asio/ip/v6_only.hpp>
#include <Asio/is_applicable_property.hpp>
#include <Asio/is_contiguous_iterator.hpp>
#include <Asio/is_executor.hpp>
#include <Asio/is_read_buffered.hpp>
#include <Asio/is_write_buffered.hpp>
#include <Asio/local/basic_endpoint.hpp>
#include <Asio/local/connect_pair.hpp>
#include <Asio/local/datagram_protocol.hpp>
#include <Asio/local/seq_packet_protocol.hpp>
#include <Asio/local/stream_protocol.hpp>
#include <Asio/multiple_exceptions.hpp>
#include <Asio/packaged_task.hpp>
#include <Asio/placeholders.hpp>
#include <Asio/posix/basic_descriptor.hpp>
#include <Asio/posix/basic_stream_descriptor.hpp>
#include <Asio/posix/descriptor.hpp>
#include <Asio/posix/descriptor_base.hpp>
#include <Asio/posix/stream_descriptor.hpp>
#include <Asio/post.hpp>
#include <Asio/prefer.hpp>
#include <Asio/prepend.hpp>
#include <Asio/query.hpp>
#include <Asio/random_access_file.hpp>
#include <Asio/read.hpp>
#include <Asio/read_at.hpp>
#include <Asio/read_until.hpp>
#include <Asio/readable_pipe.hpp>
#include <Asio/recycling_allocator.hpp>
#include <Asio/redirect_error.hpp>
#include <Asio/registered_buffer.hpp>
#include <Asio/require.hpp>
#include <Asio/require_concept.hpp>
#include <Asio/serial_port.hpp>
#include <Asio/serial_port_base.hpp>
#include <Asio/signal_set.hpp>
#include <Asio/signal_set_base.hpp>
#include <Asio/socket_base.hpp>
#include <Asio/static_thread_pool.hpp>
#include <Asio/steady_timer.hpp>
#include <Asio/strand.hpp>
#include <Asio/stream_file.hpp>
#include <Asio/streambuf.hpp>
#include <Asio/system_context.hpp>
#include <Asio/system_error.hpp>
#include <Asio/system_executor.hpp>
#include <Asio/system_timer.hpp>
#include <Asio/this_coro.hpp>
#include <Asio/thread.hpp>
#include <Asio/thread_pool.hpp>
#include <Asio/time_traits.hpp>
#include <Asio/use_awaitable.hpp>
#include <Asio/use_future.hpp>
#include <Asio/uses_executor.hpp>
#include <Asio/version.hpp>
#include <Asio/wait_traits.hpp>
#include <Asio/windows/basic_object_handle.hpp>
#include <Asio/windows/basic_overlapped_handle.hpp>
#include <Asio/windows/basic_random_access_handle.hpp>
#include <Asio/windows/basic_stream_handle.hpp>
#include <Asio/windows/object_handle.hpp>
#include <Asio/windows/overlapped_handle.hpp>
#include <Asio/windows/overlapped_ptr.hpp>
#include <Asio/windows/random_access_handle.hpp>
#include <Asio/windows/stream_handle.hpp>
#include <Asio/writable_pipe.hpp>
#include <Asio/write.hpp>
#include <Asio/write_at.hpp>

#endif // ASIO_HPP
